export type Coffin = {
  slug: string; name: string; accession: string; museum: string; location: string;
  material: string; period: string; subtitle: string; description: string; source: string; color: string;
};
export const collection: Coffin[] = [
  { slug: 'psamtikseneb', name: 'Psamtik-Seneb', accession: 'CMA 71.2254', museum: 'Chrysler Museum of Art', location: 'Norfolk, Virginia', material: 'Wood', period: 'Late Period', subtitle: 'Words for an eternal life', description: 'Follow the painted inscriptions from the central columns to the sides of the coffin. Text, image, and the protection of the gods come together on its surface.', source: 'chrysler-museum-art-712254', color: '#d8c9b6' },
  { slug: 'irethoreru', name: 'Irethoriru', accession: 'FAMSF 2002.2a–b', museum: 'Fine Arts Museums of San Francisco', location: 'San Francisco, California', material: 'Wood', period: 'Late Period', subtitle: 'A passage into the afterlife', description: 'Explore Book of the Dead spell 72 and Pyramid Text 368 across the coffin’s inscribed columns. The original viewer uses the spelling Irethoreru.', source: 'fine-arts-museums-san-francisco-20022a-b', color: '#c5c6ba' },
  { slug: 'iwefaa2', name: 'Iwefaa', accession: 'PAHMA 6-19912', museum: 'Phoebe A. Hearst Museum of Anthropology', location: 'Berkeley, California', material: 'Wood', period: 'Ancient Egypt', subtitle: 'An image of protection', description: 'A painted vignette and two lines of inscription connect image and text. Read passages combining Book of the Dead spells 51 and 52.', source: 'pahma-6-19912', color: '#d0b8a5' },
  { slug: 'anonymous1', name: 'An anonymous woman', accession: 'PAHMA 6-19927', museum: 'Phoebe A. Hearst Museum of Anthropology', location: 'Berkeley, California', material: 'Wood', period: 'Ancient Egypt', subtitle: 'A story still being read', description: 'Move around the coffin to discover inscriptions on the head, legs, basin, and feet. The source edition is a work in progress; the owner remains unidentified.', source: 'pahma-6-19927', color: '#bfc8c3' },
  { slug: 'amenirdis', name: 'Amenirdis', accession: 'PAHMA 5-1404c', museum: 'Phoebe A. Hearst Museum of Anthropology', location: 'Berkeley, California', material: 'Wood', period: 'Ancient Egypt', subtitle: 'A name, preserved', description: 'Read the offering formula down the central inscription, ending with the owner’s title and name. Its linked region encompasses the full inscription strip.', source: 'pahma-5-1404c', color: '#cfbfac' },
  { slug: 'psamtik', name: 'Psamtik', accession: 'PAHMA 5-522', museum: 'Phoebe A. Hearst Museum of Anthropology', location: 'Berkeley, California', material: 'Stone', period: '26th Dynasty', subtitle: 'The physician’s monument', description: 'This monumental sarcophagus lid belonged to a chief physician. Explore protective texts across its front, sides, and feet, and locate repeated words on the stone.', source: 'pahma-5-522', color: '#babbb4' },
];
export const getCoffin = (slug: string) => collection.find(coffin => coffin.slug === slug);
export type Region = { id: string; textId: string; direction: [number,number,number]; rotation: number; lines: number[][] };
export type Fragment = { hieroglyphs: string; hieroglyphUnicode?: string; transliteration: string; translation: string };
export type Inscription = { id: string; title: string; kind: 'inscription'|'interpretation'|'vocabulary'; description: string; fragments: Fragment[]; areaIds: string[] };
export type CoffinData = { slug: string; source: string; model: { name: string; quaternion: [number,number,number,number]; settings: number[] }; areas: Region[]; annotations: Inscription[] };
