import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import FloatingNav from '../components/FloatingNav';
import { collection } from '@/lib/collection';
export const metadata: Metadata = { title: 'Research & provenance | The Book of the Dead in 3D', description: 'The sources, annotation method, collections, and editorial choices behind six digital coffin exhibits.' };
const editions='https://sites.cs.st-andrews.ac.uk/people/mn31/egyptian/coffins/';
export default function Research(){return <>
 <a className="skip-link" href="#research">Skip to research</a><FloatingNav/>
 <main id="research" className="research-page">
  <header className="research-intro"><p className="eyebrow">RESEARCH & PROVENANCE</p><h1>Read the words.<br/><em>Keep their place.</em></h1><p>A digital encounter with an object should preserve the relationship between its surface and its scholarship.</p></header>
  <section className="research-section"><div><p className="eyebrow">01 — PURPOSE</p><h2>Text in context.</h2></div><div><p>The Berkeley Book of the Dead in 3D project studies how inscriptions relate to their positions on Egyptian coffins. Its annotated models let readers encounter texts alongside the surfaces that carry them.</p><p>This redesign presents six published models in a new reading interface. It is a prototype, not a new critical edition or a replacement for the collection records.</p><a className="text-link" href="https://3dcoffins.berkeley.edu/">The original Berkeley project <ArrowUpRight size={16}/></a></div></section>
  <section className="research-section"><div><p className="eyebrow">02 — METHOD</p><h2>A surface.<br/>A text.<br/>A connection.</h2></div><div><p>Mark-Jan Nederhof’s published viewers associate three-dimensional surface boundaries with text identifiers. An inscription, interpretation, or vocabulary entry can refer to one region or to several locations on the same object.</p><p>In this interface, selecting an outlined surface opens its linked entry. Selecting an entry focuses the model on its recorded region. Location arrows move between repeated occurrences without creating duplicate readings.</p><p>Transcriptions, transliterations, and translations retain the published edition’s content. Most hieroglyphs use Nederhof’s ResLite renderer; Amenirdis uses the source’s Unicode transcription and composed font.</p><p className="research-citation">Rita Lucarelli and Mark-Jan Nederhof, “Digitizing and Annotating Ancient Egyptian Coffins: The Book of the Dead in 3D” (2023). <a href="https://doi.org/10.1163/9789004501294_011">Read the methodology ↗</a></p></div></section>
  <section className="research-catalogue"><p className="eyebrow">03 — THE SOURCE COLLECTIONS</p><h2>Six objects, three museums.</h2><p>Each exhibit links to both its collection record and the published annotation edition. Names and accessions follow the Berkeley records; the source URL for Irethoriru retains the spelling “Irethoreru.”</p><div className="source-list">{collection.map((c,i)=><article key={c.slug}><span className="source-index">0{i+1}</span><div><h3>{c.name}</h3><p>{c.museum}<br/>{c.accession}</p></div><div className="source-links"><a href={`https://3dcoffins.berkeley.edu/coffins/${c.source}`}>Collection record ↗</a><a href={`${editions}${c.slug}/`}>Annotation edition ↗</a><Link href={`/exhibits/${c.slug}`} prefetch={false}>Enter exhibit →</Link></div></article>)}</div></section>
  <section className="research-section"><div><p className="eyebrow">04 — EDITORIAL CARE</p><h2>What changed.<br/>What remains open.</h2></div><div><p>The OBJ geometry, material files, and model textures were copied from the published St Andrews viewers. Source files and checksums are recorded in the repository’s import manifest. The supplied PhilologEg demo documents the authoring workflow; these exhibits use its published web editions, rather than newly authored mappings.</p><p>Models and annotation vertices receive the same rotation, centering, and uniform scale for display. Four display units represent the longest dimension; this is not a measurement in metres. No mesh simplification, texture repainting, or reconstruction was performed. Scan supports remain where present.</p><p>Annotation IDs, boundary coordinates, viewing directions, and one-to-many links are preserved. Headings and plain-text notes are extracted from the source HTML; photographs are resized to a maximum of 1,200 pixels and encoded as JPEGs for the collection page.</p><div className="research-note"><h3>Read with the source edition</h3><ul><li>Coverage varies. Some regions identify an entire inscription rather than individual signs.</li><li>Iwefaa’s unlinked “face” region is omitted from text selection. No annotation was invented for it.</li><li>Amenirdis and the anonymous coffin have no vocabulary entries in these imported editions.</li><li>The anonymous coffin has conflicting labels in source metadata. This interface follows the collection’s anonymous identification.</li><li>The source’s full word-level grammatical popups and critical apparatus are not reproduced. Consult the linked edition for those details.</li></ul><p>Mechanical checks confirm the imported coordinates and links. An Egyptologist should review readings, identification, transliteration fidelity, and the scholarly meaning of each mapped region.</p></div></div></section>
  <section className="research-section"><div><p className="eyebrow">05 — ACKNOWLEDGEMENTS</p><h2>Knowledge is<br/>a shared work.</h2></div><div><p>The source editions credit Rita Lucarelli, Kea Johnston, and Mark-Jan Nederhof. The Psamtik-Seneb edition additionally credits Matthew Whealton. The models are hosted by the University of St Andrews for the Berkeley project.</p><p>Collection photographs: © Chrysler Museum of Art (2019); © Fine Arts Museums of San Francisco (2018); © Phoebe A. Hearst Museum of Anthropology (2017), as stated in the respective collection records. Original assets and scholarly content remain attributable to their creators and collections; this prototype does not grant new reuse rights.</p><p>The visual design draws on the object-led presentation and editorial restraint of <a href="https://www.moma.org/">MoMA</a> and <a href="https://www.lacma.org/">LACMA</a>, with a floating-navigation interaction informed by <a href="https://ui.aceternity.com/components/floating-navbar">Aceternity UI</a>. These are design references, not institutional affiliations.</p><a className="text-link" href="https://drive.google.com/drive/folders/1APjH-mKpCwxDnktbaL-gCNNBxqhYk5Rj">Provided authoring resources <ArrowUpRight size={16}/></a></div></section>
 </main><footer className="site-footer"><Link className="wordmark" href="/">BD<span>3D</span><i/></Link><p>The Book of the Dead in 3D<br/><span>Research interface prototype</span></p><Link href="/#collection">Return to the collection <ArrowUpRight size={15}/></Link></footer>
 </>}
